### ISSUE TITLE
Недочеты

### ISSUE THREAD

**Issue by imirrori** [X-Moriarty/homework#4]
https://github.com/X-Moriarty/homework/blob/2b269fa48d0aeed5a869822087248fecf6e4e1b0/HW3_Z5/main.cpp#L6
Не используй тип float. Это мертвый тип.

https://github.com/X-Moriarty/homework/blob/2b269fa48d0aeed5a869822087248fecf6e4e1b0/HW3_Z5/main.cpp#L16
Если переменная нужна была только начиная с этой строки, тут ее объявлять и надо было.
Иначе ты делаешь присваивание значения, а нужно бы пользоваться инициализацией.

**Comment by X-Moriarty** [comment]
Внесла правки
